name: Android CI

on:
  push:
    branches: [ main,dev ]
  pull_request:
    branches: [ main,dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.0
            
    - name: Setup Java JDK  
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: 'gradle'
    - run: ./gradlew build --no-daemon
      
    
    
#     - name: Build with Gradle
#       uses: gradle/gradle-build-action@v2.1.3
      
#       run: ./gradlew build

    
